### ISSUE TITLE
System.UnauthorizedAccessException - Access to the path "/storage/emulated/0/19092018_12502659794.jpg" is denied.

### ISSUE THREAD

**Issue by Himatheja** [Xamarians/Media#2]
**Android** :
Xam.Plugin.Media is upto date
write external storage/read external storage/read input state permissions given.

**My Code** 
string filePath = GenerateFilePath();
                    _var Takeresult = await MediaService.Instance.TakePhotoAsync(new CameraOption()
                    {
                        FilePath = filePath,
                        MaxWidth = 300,
                        MaxHeight = 300
                    });_

//Throwing error above

                    if (Takeresult.IsSuccess)
                        //if (Takeresult != null && Takeresult.FilePath != null)
                        {
                        image.Source = Takeresult.FilePath;
                        string output = Takeresult.FilePath;
                        //string output = Takeresult.Replace("File: /", "");
                        var imgstringArray = output.Split('/');
                        //int count = imgstringArray.Length - 1;
                        imgdata = File.ReadAllBytes(output);
                        //UploadImageApi(upfilebytes, imgstringArray[count]);
                        imglink = Convert.ToBase64String(imgdata);
                    }
                    else {
                        await DisplayAlert("Error", Takeresult.Message, "OK");
                    }

                    break;

**Android Version**
8.0.0

**Comment by Xamarians** [comment]
Hi @Himatheja,

It seems that your project did not have access to read and write storage. You need to give permissions to access read and write storage.

Android:
-Firstly you need to tell your application that requires read and write storage access and that will be 
 done in the manifest file in your android project.
 Add this in your manifest file 
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
-Secondly you need request those access from you user as given below-
         ActivityCompat.requestPermissions(this, new String[] 
                  {Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_CODE);
iOS:
No, your app does not need special permissions as such however, scenarios do exist where the app might be unable to write to the file.

One example is if your app is using disk protection for its files, and you try to write to the folder when the disk is encrypted. Other examples are:

            -The disk is full.
            -The file is being written to by a different process (ie. you're downloading content to it in a 
              background URLSession). 
            -The path contains some invalid character (e.g. ":").
